version: '3.8'

services:
  portfolio:
    build: .
    container_name: portfolio
    networks:
      - nginx_proxy_manager_default
    restart: always

networks:
  nginx_proxy_manager_default:
    external: true
