version: '3.8'

services:
  builder:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
      - build:/app/dist
    command: sh -c "npm install && npm run build"

  web:
    image: nginx:alpine
    depends_on:
      - builder
    volumes:
      - build:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    networks:
      - nginx-proxy-manager_default

volumes:
  build:

networks:
  nginx-proxy-manager_default:
    external: true
